name: running-first-custom-action

on: [push]

jobs:
  custom-job: 
    runs-on: ubuntu-latest
    steps:
     - name: 'Checkout code'
       uses: actions/checkout@v2
     - name: 'Run custom Action'
       uses: rayventoso/customaction@main
   
